// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RHM.Infrastructure.Persistence;

#nullable disable

namespace RHM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307201933_AddMasterPatientIndex")]
    partial class AddMasterPatientIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RHM.Domain.Entities.DivipolaCode", b =>
                {
                    b.Property<string>("MunCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MunicipioNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MunCode");

                    b.HasIndex("DeptCode");

                    b.HasIndex("MunicipioNormalized");

                    b.ToTable("DivipolaCodes");

                    b.HasData(
                        new
                        {
                            MunCode = "91001",
                            Departamento = "Amazonas",
                            DeptCode = "91",
                            Municipio = "Leticia",
                            MunicipioNormalized = "LETICIA"
                        },
                        new
                        {
                            MunCode = "91263",
                            Departamento = "Amazonas",
                            DeptCode = "91",
                            Municipio = "El Encanto",
                            MunicipioNormalized = "EL ENCANTO"
                        },
                        new
                        {
                            MunCode = "05001",
                            Departamento = "Antioquia",
                            DeptCode = "05",
                            Municipio = "Medellín",
                            MunicipioNormalized = "MEDELLIN"
                        },
                        new
                        {
                            MunCode = "05088",
                            Departamento = "Antioquia",
                            DeptCode = "05",
                            Municipio = "Bello",
                            MunicipioNormalized = "BELLO"
                        },
                        new
                        {
                            MunCode = "05129",
                            Departamento = "Antioquia",
                            DeptCode = "05",
                            Municipio = "Caldas",
                            MunicipioNormalized = "CALDAS"
                        },
                        new
                        {
                            MunCode = "05212",
                            Departamento = "Antioquia",
                            DeptCode = "05",
                            Municipio = "Copacabana",
                            MunicipioNormalized = "COPACABANA"
                        },
                        new
                        {
                            MunCode = "05266",
                            Departamento = "Antioquia",
                            DeptCode = "05",
                            Municipio = "Envigado",
                            MunicipioNormalized = "ENVIGADO"
                        },
                        new
                        {
                            MunCode = "05308",
                            Departamento = "Antioquia",
                            DeptCode = "05",
                            Municipio = "Girardota",
                            MunicipioNormalized = "GIRARDOTA"
                        },
                        new
                        {
                            MunCode = "05360",
                            Departamento = "Antioquia",
                            DeptCode = "05",
                            Municipio = "Itagüí",
                            MunicipioNormalized = "ITAGUI"
                        },
                        new
                        {
                            MunCode = "05380",
                            Departamento = "Antioquia",
                            DeptCode = "05",
                            Municipio = "La Estrella",
                            MunicipioNormalized = "LA ESTRELLA"
                        },
                        new
                        {
                            MunCode = "05631",
                            Departamento = "Antioquia",
                            DeptCode = "05",
                            Municipio = "Sabaneta",
                            MunicipioNormalized = "SABANETA"
                        },
                        new
                        {
                            MunCode = "05045",
                            Departamento = "Antioquia",
                            DeptCode = "05",
                            Municipio = "Apartadó",
                            MunicipioNormalized = "APARTADO"
                        },
                        new
                        {
                            MunCode = "05147",
                            Departamento = "Antioquia",
                            DeptCode = "05",
                            Municipio = "Carepa",
                            MunicipioNormalized = "CAREPA"
                        },
                        new
                        {
                            MunCode = "05238",
                            Departamento = "Antioquia",
                            DeptCode = "05",
                            Municipio = "El Bagre",
                            MunicipioNormalized = "EL BAGRE"
                        },
                        new
                        {
                            MunCode = "05604",
                            Departamento = "Antioquia",
                            DeptCode = "05",
                            Municipio = "Rionegro",
                            MunicipioNormalized = "RIONEGRO"
                        },
                        new
                        {
                            MunCode = "05615",
                            Departamento = "Antioquia",
                            DeptCode = "05",
                            Municipio = "Samaná",
                            MunicipioNormalized = "SAMANA"
                        },
                        new
                        {
                            MunCode = "05790",
                            Departamento = "Antioquia",
                            DeptCode = "05",
                            Municipio = "Turbo",
                            MunicipioNormalized = "TURBO"
                        },
                        new
                        {
                            MunCode = "81001",
                            Departamento = "Arauca",
                            DeptCode = "81",
                            Municipio = "Arauca",
                            MunicipioNormalized = "ARAUCA"
                        },
                        new
                        {
                            MunCode = "81736",
                            Departamento = "Arauca",
                            DeptCode = "81",
                            Municipio = "Tame",
                            MunicipioNormalized = "TAME"
                        },
                        new
                        {
                            MunCode = "08001",
                            Departamento = "Atlántico",
                            DeptCode = "08",
                            Municipio = "Barranquilla",
                            MunicipioNormalized = "BARRANQUILLA"
                        },
                        new
                        {
                            MunCode = "08078",
                            Departamento = "Atlántico",
                            DeptCode = "08",
                            Municipio = "Baranoa",
                            MunicipioNormalized = "BARANOA"
                        },
                        new
                        {
                            MunCode = "08137",
                            Departamento = "Atlántico",
                            DeptCode = "08",
                            Municipio = "Campo de la Cruz",
                            MunicipioNormalized = "CAMPO DE LA CRUZ"
                        },
                        new
                        {
                            MunCode = "08296",
                            Departamento = "Atlántico",
                            DeptCode = "08",
                            Municipio = "Galapa",
                            MunicipioNormalized = "GALAPA"
                        },
                        new
                        {
                            MunCode = "08433",
                            Departamento = "Atlántico",
                            DeptCode = "08",
                            Municipio = "Malambo",
                            MunicipioNormalized = "MALAMBO"
                        },
                        new
                        {
                            MunCode = "08520",
                            Departamento = "Atlántico",
                            DeptCode = "08",
                            Municipio = "Palmar de Varela",
                            MunicipioNormalized = "PALMAR DE VARELA"
                        },
                        new
                        {
                            MunCode = "08549",
                            Departamento = "Atlántico",
                            DeptCode = "08",
                            Municipio = "Polonuevo",
                            MunicipioNormalized = "POLONUEVO"
                        },
                        new
                        {
                            MunCode = "08558",
                            Departamento = "Atlántico",
                            DeptCode = "08",
                            Municipio = "Ponedera",
                            MunicipioNormalized = "PONEDERA"
                        },
                        new
                        {
                            MunCode = "08634",
                            Departamento = "Atlántico",
                            DeptCode = "08",
                            Municipio = "Santo Tomás",
                            MunicipioNormalized = "SANTO TOMAS"
                        },
                        new
                        {
                            MunCode = "08675",
                            Departamento = "Atlántico",
                            DeptCode = "08",
                            Municipio = "Sabanagrande",
                            MunicipioNormalized = "SABANAGRANDE"
                        },
                        new
                        {
                            MunCode = "08685",
                            Departamento = "Atlántico",
                            DeptCode = "08",
                            Municipio = "Sabanalarga",
                            MunicipioNormalized = "SABANALARGA"
                        },
                        new
                        {
                            MunCode = "08758",
                            Departamento = "Atlántico",
                            DeptCode = "08",
                            Municipio = "Soledad",
                            MunicipioNormalized = "SOLEDAD"
                        },
                        new
                        {
                            MunCode = "11001",
                            Departamento = "Bogotá D.C.",
                            DeptCode = "11",
                            Municipio = "Bogotá D.C.",
                            MunicipioNormalized = "BOGOTA"
                        },
                        new
                        {
                            MunCode = "13001",
                            Departamento = "Bolívar",
                            DeptCode = "13",
                            Municipio = "Cartagena de Indias",
                            MunicipioNormalized = "CARTAGENA DE INDIAS"
                        },
                        new
                        {
                            MunCode = "13140",
                            Departamento = "Bolívar",
                            DeptCode = "13",
                            Municipio = "Calamar",
                            MunicipioNormalized = "CALAMAR"
                        },
                        new
                        {
                            MunCode = "13430",
                            Departamento = "Bolívar",
                            DeptCode = "13",
                            Municipio = "Magangué",
                            MunicipioNormalized = "MAGANGUE"
                        },
                        new
                        {
                            MunCode = "13442",
                            Departamento = "Bolívar",
                            DeptCode = "13",
                            Municipio = "Mompós",
                            MunicipioNormalized = "MOMPOS"
                        },
                        new
                        {
                            MunCode = "13620",
                            Departamento = "Bolívar",
                            DeptCode = "13",
                            Municipio = "San Juan Nepomuceno",
                            MunicipioNormalized = "SAN JUAN NEPOMUCENO"
                        },
                        new
                        {
                            MunCode = "15001",
                            Departamento = "Boyacá",
                            DeptCode = "15",
                            Municipio = "Tunja",
                            MunicipioNormalized = "TUNJA"
                        },
                        new
                        {
                            MunCode = "15176",
                            Departamento = "Boyacá",
                            DeptCode = "15",
                            Municipio = "Chiquinquirá",
                            MunicipioNormalized = "CHIQUINQUIRA"
                        },
                        new
                        {
                            MunCode = "15238",
                            Departamento = "Boyacá",
                            DeptCode = "15",
                            Municipio = "Duitama",
                            MunicipioNormalized = "DUITAMA"
                        },
                        new
                        {
                            MunCode = "15660",
                            Departamento = "Boyacá",
                            DeptCode = "15",
                            Municipio = "Sogamoso",
                            MunicipioNormalized = "SOGAMOSO"
                        },
                        new
                        {
                            MunCode = "17001",
                            Departamento = "Caldas",
                            DeptCode = "17",
                            Municipio = "Manizales",
                            MunicipioNormalized = "MANIZALES"
                        },
                        new
                        {
                            MunCode = "17042",
                            Departamento = "Caldas",
                            DeptCode = "17",
                            Municipio = "Anserma",
                            MunicipioNormalized = "ANSERMA"
                        },
                        new
                        {
                            MunCode = "17380",
                            Departamento = "Caldas",
                            DeptCode = "17",
                            Municipio = "La Dorada",
                            MunicipioNormalized = "LA DORADA"
                        },
                        new
                        {
                            MunCode = "17541",
                            Departamento = "Caldas",
                            DeptCode = "17",
                            Municipio = "Riosucio",
                            MunicipioNormalized = "RIOSUCIO"
                        },
                        new
                        {
                            MunCode = "18001",
                            Departamento = "Caquetá",
                            DeptCode = "18",
                            Municipio = "Florencia",
                            MunicipioNormalized = "FLORENCIA"
                        },
                        new
                        {
                            MunCode = "85001",
                            Departamento = "Casanare",
                            DeptCode = "85",
                            Municipio = "Yopal",
                            MunicipioNormalized = "YOPAL"
                        },
                        new
                        {
                            MunCode = "85263",
                            Departamento = "Casanare",
                            DeptCode = "85",
                            Municipio = "Paz de Ariporo",
                            MunicipioNormalized = "PAZ DE ARIPORO"
                        },
                        new
                        {
                            MunCode = "19001",
                            Departamento = "Cauca",
                            DeptCode = "19",
                            Municipio = "Popayán",
                            MunicipioNormalized = "POPAYAN"
                        },
                        new
                        {
                            MunCode = "19698",
                            Departamento = "Cauca",
                            DeptCode = "19",
                            Municipio = "Santander de Quilichao",
                            MunicipioNormalized = "SANTANDER DE QUILICHAO"
                        },
                        new
                        {
                            MunCode = "20001",
                            Departamento = "Cesar",
                            DeptCode = "20",
                            Municipio = "Valledupar",
                            MunicipioNormalized = "VALLEDUPAR"
                        },
                        new
                        {
                            MunCode = "20045",
                            Departamento = "Cesar",
                            DeptCode = "20",
                            Municipio = "Aguachica",
                            MunicipioNormalized = "AGUACHICA"
                        },
                        new
                        {
                            MunCode = "27001",
                            Departamento = "Chocó",
                            DeptCode = "27",
                            Municipio = "Quibdó",
                            MunicipioNormalized = "QUIBDO"
                        },
                        new
                        {
                            MunCode = "27413",
                            Departamento = "Chocó",
                            DeptCode = "27",
                            Municipio = "Lloró",
                            MunicipioNormalized = "LLORO"
                        },
                        new
                        {
                            MunCode = "23001",
                            Departamento = "Córdoba",
                            DeptCode = "23",
                            Municipio = "Montería",
                            MunicipioNormalized = "MONTERIA"
                        },
                        new
                        {
                            MunCode = "23162",
                            Departamento = "Córdoba",
                            DeptCode = "23",
                            Municipio = "Cereté",
                            MunicipioNormalized = "CERETE"
                        },
                        new
                        {
                            MunCode = "23464",
                            Departamento = "Córdoba",
                            DeptCode = "23",
                            Municipio = "Montelíbano",
                            MunicipioNormalized = "MONTELIBANO"
                        },
                        new
                        {
                            MunCode = "23672",
                            Departamento = "Córdoba",
                            DeptCode = "23",
                            Municipio = "Sahagún",
                            MunicipioNormalized = "SAHAGUN"
                        },
                        new
                        {
                            MunCode = "25175",
                            Departamento = "Cundinamarca",
                            DeptCode = "25",
                            Municipio = "Chía",
                            MunicipioNormalized = "CHIA"
                        },
                        new
                        {
                            MunCode = "25269",
                            Departamento = "Cundinamarca",
                            DeptCode = "25",
                            Municipio = "Facatativá",
                            MunicipioNormalized = "FACATATIVA"
                        },
                        new
                        {
                            MunCode = "25290",
                            Departamento = "Cundinamarca",
                            DeptCode = "25",
                            Municipio = "Fusagasugá",
                            MunicipioNormalized = "FUSAGASUGA"
                        },
                        new
                        {
                            MunCode = "25307",
                            Departamento = "Cundinamarca",
                            DeptCode = "25",
                            Municipio = "Girardot",
                            MunicipioNormalized = "GIRARDOT"
                        },
                        new
                        {
                            MunCode = "25430",
                            Departamento = "Cundinamarca",
                            DeptCode = "25",
                            Municipio = "Madrid",
                            MunicipioNormalized = "MADRID"
                        },
                        new
                        {
                            MunCode = "25473",
                            Departamento = "Cundinamarca",
                            DeptCode = "25",
                            Municipio = "Mosquera",
                            MunicipioNormalized = "MOSQUERA"
                        },
                        new
                        {
                            MunCode = "25486",
                            Departamento = "Cundinamarca",
                            DeptCode = "25",
                            Municipio = "Nemocón",
                            MunicipioNormalized = "NEMOCON"
                        },
                        new
                        {
                            MunCode = "25513",
                            Departamento = "Cundinamarca",
                            DeptCode = "25",
                            Municipio = "Pacho",
                            MunicipioNormalized = "PACHO"
                        },
                        new
                        {
                            MunCode = "25754",
                            Departamento = "Cundinamarca",
                            DeptCode = "25",
                            Municipio = "Soacha",
                            MunicipioNormalized = "SOACHA"
                        },
                        new
                        {
                            MunCode = "25758",
                            Departamento = "Cundinamarca",
                            DeptCode = "25",
                            Municipio = "Sogamoso",
                            MunicipioNormalized = "SOGAMOSO CUND"
                        },
                        new
                        {
                            MunCode = "25769",
                            Departamento = "Cundinamarca",
                            DeptCode = "25",
                            Municipio = "Subachoque",
                            MunicipioNormalized = "SUBACHOQUE"
                        },
                        new
                        {
                            MunCode = "25785",
                            Departamento = "Cundinamarca",
                            DeptCode = "25",
                            Municipio = "Tabio",
                            MunicipioNormalized = "TABIO"
                        },
                        new
                        {
                            MunCode = "25817",
                            Departamento = "Cundinamarca",
                            DeptCode = "25",
                            Municipio = "Tocancipá",
                            MunicipioNormalized = "TOCANCIPA"
                        },
                        new
                        {
                            MunCode = "25899",
                            Departamento = "Cundinamarca",
                            DeptCode = "25",
                            Municipio = "Zipaquirá",
                            MunicipioNormalized = "ZIPAQUIRA"
                        },
                        new
                        {
                            MunCode = "94001",
                            Departamento = "Guainía",
                            DeptCode = "94",
                            Municipio = "Inírida",
                            MunicipioNormalized = "INIRIDA"
                        },
                        new
                        {
                            MunCode = "95001",
                            Departamento = "Guaviare",
                            DeptCode = "95",
                            Municipio = "San José del Guaviare",
                            MunicipioNormalized = "SAN JOSE DEL GUAVIARE"
                        },
                        new
                        {
                            MunCode = "41001",
                            Departamento = "Huila",
                            DeptCode = "41",
                            Municipio = "Neiva",
                            MunicipioNormalized = "NEIVA"
                        },
                        new
                        {
                            MunCode = "41006",
                            Departamento = "Huila",
                            DeptCode = "41",
                            Municipio = "Acevedo",
                            MunicipioNormalized = "ACEVEDO"
                        },
                        new
                        {
                            MunCode = "41298",
                            Departamento = "Huila",
                            DeptCode = "41",
                            Municipio = "Garzón",
                            MunicipioNormalized = "GARZON"
                        },
                        new
                        {
                            MunCode = "41524",
                            Departamento = "Huila",
                            DeptCode = "41",
                            Municipio = "Pitalito",
                            MunicipioNormalized = "PITALITO"
                        },
                        new
                        {
                            MunCode = "44001",
                            Departamento = "La Guajira",
                            DeptCode = "44",
                            Municipio = "Riohacha",
                            MunicipioNormalized = "RIOHACHA"
                        },
                        new
                        {
                            MunCode = "44430",
                            Departamento = "La Guajira",
                            DeptCode = "44",
                            Municipio = "Maicao",
                            MunicipioNormalized = "MAICAO"
                        },
                        new
                        {
                            MunCode = "44560",
                            Departamento = "La Guajira",
                            DeptCode = "44",
                            Municipio = "San Juan del Cesar",
                            MunicipioNormalized = "SAN JUAN DEL CESAR"
                        },
                        new
                        {
                            MunCode = "44847",
                            Departamento = "La Guajira",
                            DeptCode = "44",
                            Municipio = "Uribia",
                            MunicipioNormalized = "URIBIA"
                        },
                        new
                        {
                            MunCode = "47001",
                            Departamento = "Magdalena",
                            DeptCode = "47",
                            Municipio = "Santa Marta",
                            MunicipioNormalized = "SANTA MARTA"
                        },
                        new
                        {
                            MunCode = "47053",
                            Departamento = "Magdalena",
                            DeptCode = "47",
                            Municipio = "Aracataca",
                            MunicipioNormalized = "ARACATACA"
                        },
                        new
                        {
                            MunCode = "47170",
                            Departamento = "Magdalena",
                            DeptCode = "47",
                            Municipio = "Ciénaga",
                            MunicipioNormalized = "CIENAGA"
                        },
                        new
                        {
                            MunCode = "47460",
                            Departamento = "Magdalena",
                            DeptCode = "47",
                            Municipio = "Mompós",
                            MunicipioNormalized = "MOMPOS MAG"
                        },
                        new
                        {
                            MunCode = "50001",
                            Departamento = "Meta",
                            DeptCode = "50",
                            Municipio = "Villavicencio",
                            MunicipioNormalized = "VILLAVICENCIO"
                        },
                        new
                        {
                            MunCode = "50006",
                            Departamento = "Meta",
                            DeptCode = "50",
                            Municipio = "Acacías",
                            MunicipioNormalized = "ACACIAS"
                        },
                        new
                        {
                            MunCode = "50313",
                            Departamento = "Meta",
                            DeptCode = "50",
                            Municipio = "Granada",
                            MunicipioNormalized = "GRANADA META"
                        },
                        new
                        {
                            MunCode = "52001",
                            Departamento = "Nariño",
                            DeptCode = "52",
                            Municipio = "Pasto",
                            MunicipioNormalized = "PASTO"
                        },
                        new
                        {
                            MunCode = "52356",
                            Departamento = "Nariño",
                            DeptCode = "52",
                            Municipio = "Ipiales",
                            MunicipioNormalized = "IPIALES"
                        },
                        new
                        {
                            MunCode = "52480",
                            Departamento = "Nariño",
                            DeptCode = "52",
                            Municipio = "La Unión",
                            MunicipioNormalized = "LA UNION NARINO"
                        },
                        new
                        {
                            MunCode = "52835",
                            Departamento = "Nariño",
                            DeptCode = "52",
                            Municipio = "Tumaco",
                            MunicipioNormalized = "TUMACO"
                        },
                        new
                        {
                            MunCode = "54001",
                            Departamento = "Norte de Santander",
                            DeptCode = "54",
                            Municipio = "Cúcuta",
                            MunicipioNormalized = "CUCUTA"
                        },
                        new
                        {
                            MunCode = "54174",
                            Departamento = "Norte de Santander",
                            DeptCode = "54",
                            Municipio = "Chinácota",
                            MunicipioNormalized = "CHINACOTA"
                        },
                        new
                        {
                            MunCode = "54206",
                            Departamento = "Norte de Santander",
                            DeptCode = "54",
                            Municipio = "Convención",
                            MunicipioNormalized = "CONVENCION"
                        },
                        new
                        {
                            MunCode = "54518",
                            Departamento = "Norte de Santander",
                            DeptCode = "54",
                            Municipio = "Ocaña",
                            MunicipioNormalized = "OCANA"
                        },
                        new
                        {
                            MunCode = "54720",
                            Departamento = "Norte de Santander",
                            DeptCode = "54",
                            Municipio = "Tibú",
                            MunicipioNormalized = "TIBU"
                        },
                        new
                        {
                            MunCode = "54810",
                            Departamento = "Norte de Santander",
                            DeptCode = "54",
                            Municipio = "Villa del Rosario",
                            MunicipioNormalized = "VILLA DEL ROSARIO"
                        },
                        new
                        {
                            MunCode = "86001",
                            Departamento = "Putumayo",
                            DeptCode = "86",
                            Municipio = "Mocoa",
                            MunicipioNormalized = "MOCOA"
                        },
                        new
                        {
                            MunCode = "86320",
                            Departamento = "Putumayo",
                            DeptCode = "86",
                            Municipio = "La Hormiga",
                            MunicipioNormalized = "LA HORMIGA"
                        },
                        new
                        {
                            MunCode = "63001",
                            Departamento = "Quindío",
                            DeptCode = "63",
                            Municipio = "Armenia",
                            MunicipioNormalized = "ARMENIA"
                        },
                        new
                        {
                            MunCode = "63111",
                            Departamento = "Quindío",
                            DeptCode = "63",
                            Municipio = "Buenavista",
                            MunicipioNormalized = "BUENAVISTA QUINDIO"
                        },
                        new
                        {
                            MunCode = "63548",
                            Departamento = "Quindío",
                            DeptCode = "63",
                            Municipio = "Quimbaya",
                            MunicipioNormalized = "QUIMBAYA"
                        },
                        new
                        {
                            MunCode = "66001",
                            Departamento = "Risaralda",
                            DeptCode = "66",
                            Municipio = "Pereira",
                            MunicipioNormalized = "PEREIRA"
                        },
                        new
                        {
                            MunCode = "66045",
                            Departamento = "Risaralda",
                            DeptCode = "66",
                            Municipio = "Apía",
                            MunicipioNormalized = "APIA"
                        },
                        new
                        {
                            MunCode = "66170",
                            Departamento = "Risaralda",
                            DeptCode = "66",
                            Municipio = "Dosquebradas",
                            MunicipioNormalized = "DOSQUEBRADAS"
                        },
                        new
                        {
                            MunCode = "66594",
                            Departamento = "Risaralda",
                            DeptCode = "66",
                            Municipio = "Santa Rosa de Cabal",
                            MunicipioNormalized = "SANTA ROSA DE CABAL"
                        },
                        new
                        {
                            MunCode = "88001",
                            Departamento = "San Andrés",
                            DeptCode = "88",
                            Municipio = "San Andrés",
                            MunicipioNormalized = "SAN ANDRES"
                        },
                        new
                        {
                            MunCode = "68001",
                            Departamento = "Santander",
                            DeptCode = "68",
                            Municipio = "Bucaramanga",
                            MunicipioNormalized = "BUCARAMANGA"
                        },
                        new
                        {
                            MunCode = "68081",
                            Departamento = "Santander",
                            DeptCode = "68",
                            Municipio = "Barrancabermeja",
                            MunicipioNormalized = "BARRANCABERMEJA"
                        },
                        new
                        {
                            MunCode = "68276",
                            Departamento = "Santander",
                            DeptCode = "68",
                            Municipio = "Floridablanca",
                            MunicipioNormalized = "FLORIDABLANCA"
                        },
                        new
                        {
                            MunCode = "68307",
                            Departamento = "Santander",
                            DeptCode = "68",
                            Municipio = "Girón",
                            MunicipioNormalized = "GIRON"
                        },
                        new
                        {
                            MunCode = "68547",
                            Departamento = "Santander",
                            DeptCode = "68",
                            Municipio = "Piedecuesta",
                            MunicipioNormalized = "PIEDECUESTA"
                        },
                        new
                        {
                            MunCode = "68615",
                            Departamento = "Santander",
                            DeptCode = "68",
                            Municipio = "Sabana de Torres",
                            MunicipioNormalized = "SABANA DE TORRES"
                        },
                        new
                        {
                            MunCode = "68679",
                            Departamento = "Santander",
                            DeptCode = "68",
                            Municipio = "San Gil",
                            MunicipioNormalized = "SAN GIL"
                        },
                        new
                        {
                            MunCode = "68755",
                            Departamento = "Santander",
                            DeptCode = "68",
                            Municipio = "Socorro",
                            MunicipioNormalized = "SOCORRO"
                        },
                        new
                        {
                            MunCode = "68780",
                            Departamento = "Santander",
                            DeptCode = "68",
                            Municipio = "Suaita",
                            MunicipioNormalized = "SUAITA"
                        },
                        new
                        {
                            MunCode = "68820",
                            Departamento = "Santander",
                            DeptCode = "68",
                            Municipio = "Vélez",
                            MunicipioNormalized = "VELEZ"
                        },
                        new
                        {
                            MunCode = "70001",
                            Departamento = "Sucre",
                            DeptCode = "70",
                            Municipio = "Sincelejo",
                            MunicipioNormalized = "SINCELEJO"
                        },
                        new
                        {
                            MunCode = "70215",
                            Departamento = "Sucre",
                            DeptCode = "70",
                            Municipio = "Corozal",
                            MunicipioNormalized = "COROZAL"
                        },
                        new
                        {
                            MunCode = "70508",
                            Departamento = "Sucre",
                            DeptCode = "70",
                            Municipio = "Ovejas",
                            MunicipioNormalized = "OVEJAS"
                        },
                        new
                        {
                            MunCode = "73001",
                            Departamento = "Tolima",
                            DeptCode = "73",
                            Municipio = "Ibagué",
                            MunicipioNormalized = "IBAGUE"
                        },
                        new
                        {
                            MunCode = "73024",
                            Departamento = "Tolima",
                            DeptCode = "73",
                            Municipio = "Alpujarra",
                            MunicipioNormalized = "ALPUJARRA"
                        },
                        new
                        {
                            MunCode = "73148",
                            Departamento = "Tolima",
                            DeptCode = "73",
                            Municipio = "Chaparral",
                            MunicipioNormalized = "CHAPARRAL"
                        },
                        new
                        {
                            MunCode = "73268",
                            Departamento = "Tolima",
                            DeptCode = "73",
                            Municipio = "Espinal",
                            MunicipioNormalized = "ESPINAL"
                        },
                        new
                        {
                            MunCode = "73349",
                            Departamento = "Tolima",
                            DeptCode = "73",
                            Municipio = "Honda",
                            MunicipioNormalized = "HONDA"
                        },
                        new
                        {
                            MunCode = "73443",
                            Departamento = "Tolima",
                            DeptCode = "73",
                            Municipio = "Melgar",
                            MunicipioNormalized = "MELGAR"
                        },
                        new
                        {
                            MunCode = "76001",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Cali",
                            MunicipioNormalized = "CALI"
                        },
                        new
                        {
                            MunCode = "76020",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Alcalá",
                            MunicipioNormalized = "ALCALA"
                        },
                        new
                        {
                            MunCode = "76036",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Andalucía",
                            MunicipioNormalized = "ANDALUCIA"
                        },
                        new
                        {
                            MunCode = "76054",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Armenia",
                            MunicipioNormalized = "ARMENIA VALLE"
                        },
                        new
                        {
                            MunCode = "76109",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Buenaventura",
                            MunicipioNormalized = "BUENAVENTURA"
                        },
                        new
                        {
                            MunCode = "76111",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Guadalajara de Buga",
                            MunicipioNormalized = "GUADALAJARA DE BUGA"
                        },
                        new
                        {
                            MunCode = "76122",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Caicedonia",
                            MunicipioNormalized = "CAICEDONIA"
                        },
                        new
                        {
                            MunCode = "76130",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Calima",
                            MunicipioNormalized = "CALIMA"
                        },
                        new
                        {
                            MunCode = "76147",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Cartago",
                            MunicipioNormalized = "CARTAGO"
                        },
                        new
                        {
                            MunCode = "76275",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Dagua",
                            MunicipioNormalized = "DAGUA"
                        },
                        new
                        {
                            MunCode = "76306",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "El Cerrito",
                            MunicipioNormalized = "EL CERRITO"
                        },
                        new
                        {
                            MunCode = "76364",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Jamundí",
                            MunicipioNormalized = "JAMUNDI"
                        },
                        new
                        {
                            MunCode = "76377",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "La Cumbre",
                            MunicipioNormalized = "LA CUMBRE"
                        },
                        new
                        {
                            MunCode = "76400",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "La Unión",
                            MunicipioNormalized = "LA UNION VALLE"
                        },
                        new
                        {
                            MunCode = "76403",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "La Victoria",
                            MunicipioNormalized = "LA VICTORIA"
                        },
                        new
                        {
                            MunCode = "76497",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Obando",
                            MunicipioNormalized = "OBANDO"
                        },
                        new
                        {
                            MunCode = "76520",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Palmira",
                            MunicipioNormalized = "PALMIRA"
                        },
                        new
                        {
                            MunCode = "76563",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Pradera",
                            MunicipioNormalized = "PRADERA"
                        },
                        new
                        {
                            MunCode = "76606",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Roldanillo",
                            MunicipioNormalized = "ROLDANILLO"
                        },
                        new
                        {
                            MunCode = "76670",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "San Pedro",
                            MunicipioNormalized = "SAN PEDRO VALLE"
                        },
                        new
                        {
                            MunCode = "76736",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Sevilla",
                            MunicipioNormalized = "SEVILLA"
                        },
                        new
                        {
                            MunCode = "76823",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Toro",
                            MunicipioNormalized = "TORO"
                        },
                        new
                        {
                            MunCode = "76828",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Trujillo",
                            MunicipioNormalized = "TRUJILLO"
                        },
                        new
                        {
                            MunCode = "76845",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Tuluá",
                            MunicipioNormalized = "TULUA"
                        },
                        new
                        {
                            MunCode = "76863",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Ulloa",
                            MunicipioNormalized = "ULLOA"
                        },
                        new
                        {
                            MunCode = "76869",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Versalles",
                            MunicipioNormalized = "VERSALLES"
                        },
                        new
                        {
                            MunCode = "76890",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Vijes",
                            MunicipioNormalized = "VIJES"
                        },
                        new
                        {
                            MunCode = "76892",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Yotoco",
                            MunicipioNormalized = "YOTOCO"
                        },
                        new
                        {
                            MunCode = "76895",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Yumbo",
                            MunicipioNormalized = "YUMBO"
                        },
                        new
                        {
                            MunCode = "76897",
                            Departamento = "Valle del Cauca",
                            DeptCode = "76",
                            Municipio = "Zarzal",
                            MunicipioNormalized = "ZARZAL"
                        },
                        new
                        {
                            MunCode = "97001",
                            Departamento = "Vaupés",
                            DeptCode = "97",
                            Municipio = "Mitú",
                            MunicipioNormalized = "MITU"
                        },
                        new
                        {
                            MunCode = "99001",
                            Departamento = "Vichada",
                            DeptCode = "99",
                            Municipio = "Puerto Carreño",
                            MunicipioNormalized = "PUERTO CARRENO"
                        });
                });

            modelBuilder.Entity("RHM.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BiologicalSex")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DivipolaDeptCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("DivipolaMunCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "DocType", "DocNumber")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("RHM.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("RHM.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("RHM.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ContactEmail")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("RHM.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RHM.Domain.Entities.Patient", b =>
                {
                    b.HasOne("RHM.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RHM.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("RHM.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RHM.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("RHM.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RHM.Domain.Entities.User", b =>
                {
                    b.HasOne("RHM.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RHM.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Subscriptions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RHM.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
